const ENUM_USER_ROLE = {
  LEADER: 'LEADER',
  MEMBER: 'MEMBER',
};

const ENUM_PROJECT_TYPE = {
  FRONTEND_ONLY: 'FRONTEND_ONLY',
  UI_ONLY: 'UI_ONLY',
  FULL_STACK: 'FULL_STACK',
};

const ENUM_PROJECT_PHASE = {
  FRONTEND: 'FRONTEND',
  BACKEND: 'BACKEND',
  UI: 'UI',
};

const ENUM_PROJECT_PRIORITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
};

const ENUM_NOTIFICATION_TYPE = {
  DEADLINE: 'DEADLINE',
  PROJECT_UPDATE: 'PROJECT_UPDATE',
  CHAT: 'CHAT',
  NOTICE: 'NOTICE',
  APPROVAL: 'APPROVAL',
};

module.exports = {
  ENUM_USER_ROLE,
  ENUM_PROJECT_TYPE,
  ENUM_PROJECT_PHASE,
  ENUM_PROJECT_PRIORITY,
  ENUM_NOTIFICATION_TYPE,
}; 